server:
  port: 9200
spring:
  application:
    name: mybaits-boot-samples
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://edgclearlove.top:3306/test?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=5
      username: root
      password: 123456
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:com/lyle/samples/mybaits/samples/mapper/xml/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.lyle.samples.mybaits.samples.entity  # 注意：对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.lyle.samples.mybaits.samples: debug
